export type Category =
  | "AI"
  | "Developer tools"
  | "Infrastructure"
  | "Fintech"
  | "Commerce"
  | "Consumer";

export type Company = {
  org: string;
  name: string;
  category: Category;
  description: string;
};

export const companies: Company[] = [
  { org: "vercel", name: "Vercel", category: "Developer tools", description: "Frontend cloud" },
  { org: "stripe", name: "Stripe", category: "Fintech", description: "Financial infrastructure" },
  { org: "github", name: "GitHub", category: "Developer tools", description: "Developer platform" },
  { org: "supabase", name: "Supabase", category: "Developer tools", description: "Open source backend" },
  { org: "linear", name: "Linear", category: "Developer tools", description: "Product development" },
  { org: "cloudflare", name: "Cloudflare", category: "Infrastructure", description: "Connectivity cloud" },
  { org: "shopify", name: "Shopify", category: "Commerce", description: "Commerce platform" },
  { org: "openai", name: "OpenAI", category: "AI", description: "AI research and products" },
  { org: "anthropics", name: "Anthropic", category: "AI", description: "AI safety and research" },
  { org: "huggingface", name: "Hugging Face", category: "AI", description: "Open machine learning" },
  { org: "langchain-ai", name: "LangChain", category: "AI", description: "Agent engineering" },
  { org: "mistralai", name: "Mistral AI", category: "AI", description: "Frontier AI" },
  { org: "elevenlabs", name: "ElevenLabs", category: "AI", description: "Voice AI" },
  { org: "replicate", name: "Replicate", category: "AI", description: "Run AI models" },
  { org: "run-llama", name: "LlamaIndex", category: "AI", description: "AI data framework" },
  { org: "ollama", name: "Ollama", category: "AI", description: "Local AI models" },
  { org: "nvidia", name: "NVIDIA", category: "AI", description: "Accelerated computing" },
  { org: "google-deepmind", name: "Google DeepMind", category: "AI", description: "AI research" },
  { org: "xai-org", name: "xAI", category: "AI", description: "Frontier AI" },
  { org: "cohere-ai", name: "Cohere", category: "AI", description: "Enterprise AI" },
  { org: "stability-ai", name: "Stability AI", category: "AI", description: "Generative AI" },
  { org: "togethercomputer", name: "Together AI", category: "AI", description: "AI acceleration cloud" },
  { org: "groq", name: "Groq", category: "AI", description: "AI inference" },
  { org: "perplexityai", name: "Perplexity", category: "AI", description: "AI search" },
  { org: "ai21labs", name: "AI21 Labs", category: "AI", description: "Language models" },
  { org: "cerebras", name: "Cerebras", category: "AI", description: "AI compute" },
  { org: "modal-labs", name: "Modal", category: "AI", description: "AI infrastructure" },
  { org: "anyscale", name: "Anyscale", category: "AI", description: "AI compute platform" },
  { org: "wandb", name: "Weights & Biases", category: "AI", description: "AI developer platform" },
  { org: "pinecone-io", name: "Pinecone", category: "AI", description: "Vector database" },
  { org: "qdrant", name: "Qdrant", category: "AI", description: "Vector search" },
  { org: "weaviate", name: "Weaviate", category: "AI", description: "AI-native database" },
  { org: "milvus-io", name: "Milvus", category: "AI", description: "Vector database" },
  { org: "chroma-core", name: "Chroma", category: "AI", description: "AI data infrastructure" },
  { org: "deepseek-ai", name: "DeepSeek", category: "AI", description: "AI research" },
  { org: "figma", name: "Figma", category: "Developer tools", description: "Collaborative design" },
  { org: "gitlabhq", name: "GitLab", category: "Developer tools", description: "DevSecOps platform" },
  { org: "jetbrains", name: "JetBrains", category: "Developer tools", description: "Developer tools" },
  { org: "postmanlabs", name: "Postman", category: "Developer tools", description: "API platform" },
  { org: "prisma", name: "Prisma", category: "Developer tools", description: "Type-safe database tools" },
  { org: "getsentry", name: "Sentry", category: "Developer tools", description: "Application monitoring" },
  { org: "storybookjs", name: "Storybook", category: "Developer tools", description: "UI development" },
  { org: "withastro", name: "Astro", category: "Developer tools", description: "Web framework" },
  { org: "remix-run", name: "Remix", category: "Developer tools", description: "Web framework" },
  { org: "tailwindlabs", name: "Tailwind Labs", category: "Developer tools", description: "CSS tooling" },
  { org: "notion", name: "Notion", category: "Developer tools", description: "Connected workspace" },
  { org: "calcom", name: "Cal.com", category: "Developer tools", description: "Scheduling infrastructure" },
  { org: "mattermost", name: "Mattermost", category: "Developer tools", description: "Collaboration platform" },
  { org: "denoland", name: "Deno", category: "Developer tools", description: "JavaScript runtime" },
  { org: "rust-lang", name: "Rust", category: "Developer tools", description: "Programming language" },
  { org: "nodejs", name: "Node.js", category: "Developer tools", description: "JavaScript runtime" },
  { org: "mozilla", name: "Mozilla", category: "Developer tools", description: "Open internet technology" },
  { org: "twilio", name: "Twilio", category: "Developer tools", description: "Customer communications" },
  { org: "oven-sh", name: "Bun", category: "Developer tools", description: "JavaScript runtime" },
  { org: "nrwl", name: "Nx", category: "Developer tools", description: "Build system" },
  { org: "expo", name: "Expo", category: "Developer tools", description: "App development platform" },
  { org: "cypress-io", name: "Cypress", category: "Developer tools", description: "Web testing" },
  { org: "browserbase", name: "Browserbase", category: "Developer tools", description: "Browser infrastructure" },
  { org: "triggerdotdev", name: "Trigger.dev", category: "Developer tools", description: "Background jobs" },
  { org: "temporalio", name: "Temporal", category: "Developer tools", description: "Durable execution" },
  { org: "inngest", name: "Inngest", category: "Developer tools", description: "Event-driven functions" },
  { org: "resend", name: "Resend", category: "Developer tools", description: "Email for developers" },
  { org: "dubinc", name: "Dub", category: "Developer tools", description: "Link infrastructure" },
  { org: "unkeyed", name: "Unkey", category: "Developer tools", description: "API infrastructure" },
  { org: "trpc", name: "tRPC", category: "Developer tools", description: "Type-safe APIs" },
  { org: "atlassian", name: "Atlassian", category: "Developer tools", description: "Team software" },
  { org: "microsoft", name: "Microsoft", category: "Infrastructure", description: "Software and cloud" },
  { org: "google", name: "Google", category: "Infrastructure", description: "Technology platform" },
  { org: "aws", name: "AWS", category: "Infrastructure", description: "Cloud computing" },
  { org: "docker", name: "Docker", category: "Infrastructure", description: "Application containers" },
  { org: "kubernetes", name: "Kubernetes", category: "Infrastructure", description: "Container orchestration" },
  { org: "hashicorp", name: "HashiCorp", category: "Infrastructure", description: "Cloud infrastructure" },
  { org: "grafana", name: "Grafana Labs", category: "Infrastructure", description: "Observability" },
  { org: "elastic", name: "Elastic", category: "Infrastructure", description: "Search and observability" },
  { org: "mongodb", name: "MongoDB", category: "Infrastructure", description: "Developer data platform" },
  { org: "cockroachdb", name: "Cockroach Labs", category: "Infrastructure", description: "Distributed SQL" },
  { org: "planetscale", name: "PlanetScale", category: "Infrastructure", description: "Database platform" },
  { org: "databricks", name: "Databricks", category: "Infrastructure", description: "Data and AI" },
  { org: "datadog", name: "Datadog", category: "Infrastructure", description: "Cloud monitoring" },
  { org: "railwayapp", name: "Railway", category: "Infrastructure", description: "Application infrastructure" },
  { org: "fly-apps", name: "Fly.io", category: "Infrastructure", description: "Application platform" },
  { org: "pulumi", name: "Pulumi", category: "Infrastructure", description: "Infrastructure as code" },
  { org: "digitalocean", name: "DigitalOcean", category: "Infrastructure", description: "Developer cloud" },
  { org: "heroku", name: "Heroku", category: "Infrastructure", description: "Cloud application platform" },
  { org: "canonical", name: "Canonical", category: "Infrastructure", description: "Ubuntu and open source" },
  { org: "redhat-developer", name: "Red Hat", category: "Infrastructure", description: "Enterprise open source" },
  { org: "prometheus", name: "Prometheus", category: "Infrastructure", description: "Systems monitoring" },
  { org: "open-telemetry", name: "OpenTelemetry", category: "Infrastructure", description: "Observability framework" },
  { org: "fastly", name: "Fastly", category: "Infrastructure", description: "Edge cloud" },
  { org: "akamai", name: "Akamai", category: "Infrastructure", description: "Connected cloud" },
  { org: "oracle", name: "Oracle", category: "Infrastructure", description: "Cloud and databases" },
  { org: "alibaba", name: "Alibaba", category: "Infrastructure", description: "Cloud technology" },
  { org: "tencent", name: "Tencent", category: "Infrastructure", description: "Cloud technology" },
  { org: "ibm", name: "IBM", category: "Infrastructure", description: "Enterprise technology" },
  { org: "intel", name: "Intel", category: "Infrastructure", description: "Computing platforms" },
  { org: "amd", name: "AMD", category: "Infrastructure", description: "High-performance computing" },
  { org: "arm-software", name: "Arm", category: "Infrastructure", description: "Computing architecture" },
  { org: "confluentinc", name: "Confluent", category: "Infrastructure", description: "Data streaming" },
  { org: "apache", name: "Apache", category: "Infrastructure", description: "Open source software" },
  { org: "redis", name: "Redis", category: "Infrastructure", description: "Data platform" },
  { org: "valkey-io", name: "Valkey", category: "Infrastructure", description: "In-memory data store" },
  { org: "timescale", name: "Tiger Data", category: "Infrastructure", description: "Postgres data platform" },
  { org: "clickhouse", name: "ClickHouse", category: "Infrastructure", description: "Analytics database" },
  { org: "scylladb", name: "ScyllaDB", category: "Infrastructure", description: "Distributed database" },
  { org: "neondatabase", name: "Neon", category: "Infrastructure", description: "Serverless Postgres" },
  { org: "upstash", name: "Upstash", category: "Infrastructure", description: "Serverless data" },
  { org: "koyeb", name: "Koyeb", category: "Infrastructure", description: "Application platform" },
  { org: "snowflakedb", name: "Snowflake", category: "Infrastructure", description: "Data cloud" },
  { org: "duckdb", name: "DuckDB", category: "Infrastructure", description: "Analytical database" },
  { org: "motherduckdb", name: "MotherDuck", category: "Infrastructure", description: "Cloud analytics" },
  { org: "dbt-labs", name: "dbt Labs", category: "Infrastructure", description: "Analytics engineering" },
  { org: "airbytehq", name: "Airbyte", category: "Infrastructure", description: "Data movement" },
  { org: "coinbase", name: "Coinbase", category: "Fintech", description: "Crypto platform" },
  { org: "block", name: "Block", category: "Fintech", description: "Financial services" },
  { org: "transferwise", name: "Wise", category: "Fintech", description: "International money" },
  { org: "adyen", name: "Adyen", category: "Fintech", description: "Payments platform" },
  { org: "plaid", name: "Plaid", category: "Fintech", description: "Financial data network" },
  { org: "klarna", name: "Klarna", category: "Fintech", description: "Payments and shopping" },
  { org: "monzo", name: "Monzo", category: "Fintech", description: "Digital banking" },
  { org: "nubank", name: "Nubank", category: "Fintech", description: "Digital financial services" },
  { org: "affirm", name: "Affirm", category: "Fintech", description: "Payment network" },
  { org: "brex", name: "Brex", category: "Fintech", description: "Financial software" },
  { org: "robinhood", name: "Robinhood", category: "Fintech", description: "Financial markets" },
  { org: "checkout", name: "Checkout.com", category: "Fintech", description: "Payments platform" },
  { org: "paypal", name: "PayPal", category: "Fintech", description: "Digital payments" },
  { org: "thought-machine", name: "Thought Machine", category: "Fintech", description: "Cloud banking" },
  { org: "automattic", name: "Automattic", category: "Commerce", description: "Open web products" },
  { org: "woocommerce", name: "WooCommerce", category: "Commerce", description: "Open source commerce" },
  { org: "medusajs", name: "Medusa", category: "Commerce", description: "Commerce infrastructure" },
  { org: "saleor", name: "Saleor", category: "Commerce", description: "Composable commerce" },
  { org: "bigcommerce", name: "BigCommerce", category: "Commerce", description: "Commerce platform" },
  { org: "wix", name: "Wix", category: "Commerce", description: "Website and commerce platform" },
  { org: "etsy", name: "Etsy", category: "Commerce", description: "Creative marketplace" },
  { org: "instacart", name: "Instacart", category: "Commerce", description: "Grocery technology" },
  { org: "doordash", name: "DoorDash", category: "Commerce", description: "Local commerce" },
  { org: "deliveroo", name: "Deliveroo", category: "Commerce", description: "Delivery marketplace" },
  { org: "netflix", name: "Netflix", category: "Consumer", description: "Entertainment" },
  { org: "airbnb", name: "Airbnb", category: "Consumer", description: "Travel marketplace" },
  { org: "uber", name: "Uber", category: "Consumer", description: "Mobility platform" },
  { org: "spotify", name: "Spotify", category: "Consumer", description: "Audio streaming" },
  { org: "discord", name: "Discord", category: "Consumer", description: "Social communication" },
  { org: "reddit", name: "Reddit", category: "Consumer", description: "Community network" },
  { org: "pinterest", name: "Pinterest", category: "Consumer", description: "Visual discovery" },
  { org: "dropbox", name: "Dropbox", category: "Consumer", description: "Cloud content" },
  { org: "facebook", name: "Meta", category: "Consumer", description: "Social technology" },
  { org: "apple", name: "Apple", category: "Consumer", description: "Consumer technology" },
  { org: "linkedin", name: "LinkedIn", category: "Consumer", description: "Professional network" },
  { org: "slackhq", name: "Slack", category: "Consumer", description: "Work communication" },
  { org: "zoom", name: "Zoom", category: "Consumer", description: "Video communications" },
  { org: "bytedance", name: "ByteDance", category: "Consumer", description: "Content platforms" },
  { org: "twitter", name: "X", category: "Consumer", description: "Social network" },
  { org: "snapchat", name: "Snap", category: "Consumer", description: "Visual communication" },
  { org: "lyft", name: "Lyft", category: "Consumer", description: "Mobility platform" },
  { org: "strava", name: "Strava", category: "Consumer", description: "Active community" },
  { org: "duolingo", name: "Duolingo", category: "Consumer", description: "Language learning" },
  { org: "canva", name: "Canva", category: "Consumer", description: "Visual communication" },
  { org: "adobe", name: "Adobe", category: "Consumer", description: "Creative software" },
  { org: "samsung", name: "Samsung", category: "Consumer", description: "Consumer technology" },
  { org: "sony", name: "Sony", category: "Consumer", description: "Entertainment technology" },
  { org: "roblox", name: "Roblox", category: "Consumer", description: "Immersive platform" },
  { org: "unity-technologies", name: "Unity", category: "Consumer", description: "Real-time development" },
  { org: "signalapp", name: "Signal", category: "Consumer", description: "Private messaging" },
  { org: "protonmail", name: "Proton", category: "Consumer", description: "Privacy services" },
  { org: "1password", name: "1Password", category: "Consumer", description: "Identity security" },
  { org: "bitwarden", name: "Bitwarden", category: "Consumer", description: "Password management" },
  { org: "zapier", name: "Zapier", category: "Consumer", description: "Workflow automation" },
  { org: "asana", name: "Asana", category: "Consumer", description: "Work management" },
  { org: "mondaycom", name: "monday.com", category: "Consumer", description: "Work platform" },
];

export const categories = [
  "All",
  "AI",
  "Developer tools",
  "Infrastructure",
  "Fintech",
  "Commerce",
  "Consumer",
] as const;
