export type Category =
  | "Featured"
  | "AI"
  | "Developer tools"
  | "Infrastructure"
  | "Fintech"
  | "Commerce"
  | "Consumer";

export type Company = {
  org: string;
  name: string;
  category: Category;
  description: string;
};

export const companies: Company[] = [
  { org: "vercel", name: "Vercel", category: "Featured", description: "Frontend cloud" },
  { org: "stripe", name: "Stripe", category: "Featured", description: "Financial infrastructure" },
  { org: "github", name: "GitHub", category: "Featured", description: "Developer platform" },
  { org: "supabase", name: "Supabase", category: "Featured", description: "Open source backend" },
  { org: "linear", name: "Linear", category: "Featured", description: "Product development" },
  { org: "cloudflare", name: "Cloudflare", category: "Featured", description: "Connectivity cloud" },
  { org: "shopify", name: "Shopify", category: "Featured", description: "Commerce platform" },
  { org: "openai", name: "OpenAI", category: "AI", description: "AI research and products" },
  { org: "anthropics", name: "Anthropic", category: "AI", description: "AI safety and research" },
  { org: "huggingface", name: "Hugging Face", category: "AI", description: "Open machine learning" },
  { org: "langchain-ai", name: "LangChain", category: "AI", description: "Agent engineering" },
  { org: "mistralai", name: "Mistral AI", category: "AI", description: "Frontier AI" },
  { org: "elevenlabs", name: "ElevenLabs", category: "AI", description: "Voice AI" },
  { org: "replicate", name: "Replicate", category: "AI", description: "Run AI models" },
  { org: "run-llama", name: "LlamaIndex", category: "AI", description: "AI data framework" },
  { org: "ollama", name: "Ollama", category: "AI", description: "Local AI models" },
  { org: "nvidia", name: "NVIDIA", category: "AI", description: "Accelerated computing" },
  { org: "figma", name: "Figma", category: "Developer tools", description: "Collaborative design" },
  { org: "gitlabhq", name: "GitLab", category: "Developer tools", description: "DevSecOps platform" },
  { org: "jetbrains", name: "JetBrains", category: "Developer tools", description: "Developer tools" },
  { org: "postmanlabs", name: "Postman", category: "Developer tools", description: "API platform" },
  { org: "prisma", name: "Prisma", category: "Developer tools", description: "Type-safe database tools" },
  { org: "getsentry", name: "Sentry", category: "Developer tools", description: "Application monitoring" },
  { org: "storybookjs", name: "Storybook", category: "Developer tools", description: "UI development" },
  { org: "withastro", name: "Astro", category: "Developer tools", description: "Web framework" },
  { org: "remix-run", name: "Remix", category: "Developer tools", description: "Web framework" },
  { org: "tailwindlabs", name: "Tailwind Labs", category: "Developer tools", description: "CSS tooling" },
  { org: "notion", name: "Notion", category: "Developer tools", description: "Connected workspace" },
  { org: "calcom", name: "Cal.com", category: "Developer tools", description: "Scheduling infrastructure" },
  { org: "mattermost", name: "Mattermost", category: "Developer tools", description: "Collaboration platform" },
  { org: "denoland", name: "Deno", category: "Developer tools", description: "JavaScript runtime" },
  { org: "rust-lang", name: "Rust", category: "Developer tools", description: "Programming language" },
  { org: "nodejs", name: "Node.js", category: "Developer tools", description: "JavaScript runtime" },
  { org: "mozilla", name: "Mozilla", category: "Developer tools", description: "Open internet technology" },
  { org: "twilio", name: "Twilio", category: "Developer tools", description: "Customer communications" },
  { org: "microsoft", name: "Microsoft", category: "Infrastructure", description: "Software and cloud" },
  { org: "google", name: "Google", category: "Infrastructure", description: "Technology platform" },
  { org: "aws", name: "AWS", category: "Infrastructure", description: "Cloud computing" },
  { org: "docker", name: "Docker", category: "Infrastructure", description: "Application containers" },
  { org: "kubernetes", name: "Kubernetes", category: "Infrastructure", description: "Container orchestration" },
  { org: "hashicorp", name: "HashiCorp", category: "Infrastructure", description: "Cloud infrastructure" },
  { org: "grafana", name: "Grafana Labs", category: "Infrastructure", description: "Observability" },
  { org: "elastic", name: "Elastic", category: "Infrastructure", description: "Search and observability" },
  { org: "mongodb", name: "MongoDB", category: "Infrastructure", description: "Developer data platform" },
  { org: "cockroachdb", name: "Cockroach Labs", category: "Infrastructure", description: "Distributed SQL" },
  { org: "planetscale", name: "PlanetScale", category: "Infrastructure", description: "Database platform" },
  { org: "databricks", name: "Databricks", category: "Infrastructure", description: "Data and AI" },
  { org: "datadog", name: "Datadog", category: "Infrastructure", description: "Cloud monitoring" },
  { org: "railwayapp", name: "Railway", category: "Infrastructure", description: "Application infrastructure" },
  { org: "fly-apps", name: "Fly.io", category: "Infrastructure", description: "Application platform" },
  { org: "pulumi", name: "Pulumi", category: "Infrastructure", description: "Infrastructure as code" },
  { org: "digitalocean", name: "DigitalOcean", category: "Infrastructure", description: "Developer cloud" },
  { org: "heroku", name: "Heroku", category: "Infrastructure", description: "Cloud application platform" },
  { org: "canonical", name: "Canonical", category: "Infrastructure", description: "Ubuntu and open source" },
  { org: "redhat-developer", name: "Red Hat", category: "Infrastructure", description: "Enterprise open source" },
  { org: "prometheus", name: "Prometheus", category: "Infrastructure", description: "Systems monitoring" },
  { org: "open-telemetry", name: "OpenTelemetry", category: "Infrastructure", description: "Observability framework" },
  { org: "coinbase", name: "Coinbase", category: "Fintech", description: "Crypto platform" },
  { org: "block", name: "Block", category: "Fintech", description: "Financial services" },
  { org: "wise", name: "Wise", category: "Fintech", description: "International money" },
  { org: "adyen", name: "Adyen", category: "Fintech", description: "Payments platform" },
  { org: "plaid", name: "Plaid", category: "Fintech", description: "Financial data network" },
  { org: "klarna", name: "Klarna", category: "Fintech", description: "Payments and shopping" },
  { org: "monzo", name: "Monzo", category: "Fintech", description: "Digital banking" },
  { org: "nubank", name: "Nubank", category: "Fintech", description: "Digital financial services" },
  { org: "affirm", name: "Affirm", category: "Fintech", description: "Payment network" },
  { org: "brex", name: "Brex", category: "Fintech", description: "Financial software" },
  { org: "robinhood", name: "Robinhood", category: "Fintech", description: "Financial markets" },
  { org: "automattic", name: "Automattic", category: "Commerce", description: "Open web products" },
  { org: "woocommerce", name: "WooCommerce", category: "Commerce", description: "Open source commerce" },
  { org: "medusajs", name: "Medusa", category: "Commerce", description: "Commerce infrastructure" },
  { org: "saleor", name: "Saleor", category: "Commerce", description: "Composable commerce" },
  { org: "netflix", name: "Netflix", category: "Consumer", description: "Entertainment" },
  { org: "airbnb", name: "Airbnb", category: "Consumer", description: "Travel marketplace" },
  { org: "uber", name: "Uber", category: "Consumer", description: "Mobility platform" },
  { org: "spotify", name: "Spotify", category: "Consumer", description: "Audio streaming" },
  { org: "discord", name: "Discord", category: "Consumer", description: "Social communication" },
  { org: "reddit", name: "Reddit", category: "Consumer", description: "Community network" },
  { org: "pinterest", name: "Pinterest", category: "Consumer", description: "Visual discovery" },
  { org: "dropbox", name: "Dropbox", category: "Consumer", description: "Cloud content" },
  { org: "facebook", name: "Meta", category: "Consumer", description: "Social technology" },
  { org: "apple", name: "Apple", category: "Consumer", description: "Consumer technology" },
  { org: "linkedin", name: "LinkedIn", category: "Consumer", description: "Professional network" },
  { org: "slackhq", name: "Slack", category: "Consumer", description: "Work communication" },
  { org: "zoom", name: "Zoom", category: "Consumer", description: "Video communications" },
];

export const categories = [
  "All",
  "Featured",
  "AI",
  "Developer tools",
  "Infrastructure",
  "Fintech",
  "Commerce",
  "Consumer",
] as const;
